version: '3'

services:

  web:
    image: soundgif-web:latest
    ports:
      - 80:80
    depends_on:
      - api

  api:
    image: soundgif-api:latest
    ports: 
      - 3000:3000
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/initdb/create_database.sh:/docker-entrypoint-initdb.d/create_database.sh


  
